"""
mmsi_lookup.py — Maritime Identification Digits (MID) → flag country lookup.
First 3 digits of MMSI = MID code assigned by ITU.
"""

MID_TABLE = {
    "201": {"country": "Albania",                  "iso2": "AL", "flag": "🇦🇱"},
    "202": {"country": "Andorra",                  "iso2": "AD", "flag": "🇦🇩"},
    "203": {"country": "Austria",                  "iso2": "AT", "flag": "🇦🇹"},
    "204": {"country": "Portugal",                 "iso2": "PT", "flag": "🇵🇹"},
    "205": {"country": "Belgium",                  "iso2": "BE", "flag": "🇧🇪"},
    "206": {"country": "Belarus",                  "iso2": "BY", "flag": "🇧🇾"},
    "207": {"country": "Bulgaria",                 "iso2": "BG", "flag": "🇧🇬"},
    "208": {"country": "Vatican City",             "iso2": "VA", "flag": "🇻🇦"},
    "209": {"country": "Cyprus",                   "iso2": "CY", "flag": "🇨🇾"},
    "210": {"country": "Cyprus",                   "iso2": "CY", "flag": "🇨🇾"},
    "211": {"country": "Germany",                  "iso2": "DE", "flag": "🇩🇪"},
    "212": {"country": "Cyprus",                   "iso2": "CY", "flag": "🇨🇾"},
    "213": {"country": "Georgia",                  "iso2": "GE", "flag": "🇬🇪"},
    "214": {"country": "Moldova",                  "iso2": "MD", "flag": "🇲🇩"},
    "215": {"country": "Malta",                    "iso2": "MT", "flag": "🇲🇹"},
    "216": {"country": "Armenia",                  "iso2": "AM", "flag": "🇦🇲"},
    "218": {"country": "Germany",                  "iso2": "DE", "flag": "🇩🇪"},
    "219": {"country": "Denmark",                  "iso2": "DK", "flag": "🇩🇰"},
    "220": {"country": "Denmark",                  "iso2": "DK", "flag": "🇩🇰"},
    "224": {"country": "Spain",                    "iso2": "ES", "flag": "🇪🇸"},
    "225": {"country": "Spain",                    "iso2": "ES", "flag": "🇪🇸"},
    "226": {"country": "France",                   "iso2": "FR", "flag": "🇫🇷"},
    "227": {"country": "France",                   "iso2": "FR", "flag": "🇫🇷"},
    "228": {"country": "France",                   "iso2": "FR", "flag": "🇫🇷"},
    "230": {"country": "Finland",                  "iso2": "FI", "flag": "🇫🇮"},
    "231": {"country": "Faroe Islands",            "iso2": "FO", "flag": "🇫🇴"},
    "232": {"country": "United Kingdom",           "iso2": "GB", "flag": "🇬🇧"},
    "233": {"country": "United Kingdom",           "iso2": "GB", "flag": "🇬🇧"},
    "234": {"country": "United Kingdom",           "iso2": "GB", "flag": "🇬🇧"},
    "235": {"country": "United Kingdom",           "iso2": "GB", "flag": "🇬🇧"},
    "236": {"country": "Gibraltar",                "iso2": "GI", "flag": "🇬🇮"},
    "237": {"country": "Greece",                   "iso2": "GR", "flag": "🇬🇷"},
    "238": {"country": "Croatia",                  "iso2": "HR", "flag": "🇭🇷"},
    "239": {"country": "Greece",                   "iso2": "GR", "flag": "🇬🇷"},
    "240": {"country": "Greece",                   "iso2": "GR", "flag": "🇬🇷"},
    "241": {"country": "Greece",                   "iso2": "GR", "flag": "🇬🇷"},
    "242": {"country": "Morocco",                  "iso2": "MA", "flag": "🇲🇦"},
    "243": {"country": "Hungary",                  "iso2": "HU", "flag": "🇭🇺"},
    "244": {"country": "Netherlands",              "iso2": "NL", "flag": "🇳🇱"},
    "245": {"country": "Netherlands",              "iso2": "NL", "flag": "🇳🇱"},
    "246": {"country": "Netherlands",              "iso2": "NL", "flag": "🇳🇱"},
    "247": {"country": "Italy",                    "iso2": "IT", "flag": "🇮🇹"},
    "248": {"country": "Malta",                    "iso2": "MT", "flag": "🇲🇹"},
    "249": {"country": "Malta",                    "iso2": "MT", "flag": "🇲🇹"},
    "250": {"country": "Ireland",                  "iso2": "IE", "flag": "🇮🇪"},
    "251": {"country": "Iceland",                  "iso2": "IS", "flag": "🇮🇸"},
    "252": {"country": "Liechtenstein",            "iso2": "LI", "flag": "🇱🇮"},
    "253": {"country": "Luxembourg",               "iso2": "LU", "flag": "🇱🇺"},
    "254": {"country": "Monaco",                   "iso2": "MC", "flag": "🇲🇨"},
    "255": {"country": "Portugal",                 "iso2": "PT", "flag": "🇵🇹"},
    "256": {"country": "Malta",                    "iso2": "MT", "flag": "🇲🇹"},
    "257": {"country": "Norway",                   "iso2": "NO", "flag": "🇳🇴"},
    "258": {"country": "Norway",                   "iso2": "NO", "flag": "🇳🇴"},
    "259": {"country": "Norway",                   "iso2": "NO", "flag": "🇳🇴"},
    "261": {"country": "Poland",                   "iso2": "PL", "flag": "🇵🇱"},
    "262": {"country": "Montenegro",               "iso2": "ME", "flag": "🇲🇪"},
    "263": {"country": "Portugal",                 "iso2": "PT", "flag": "🇵🇹"},
    "264": {"country": "Romania",                  "iso2": "RO", "flag": "🇷🇴"},
    "265": {"country": "Sweden",                   "iso2": "SE", "flag": "🇸🇪"},
    "266": {"country": "Sweden",                   "iso2": "SE", "flag": "🇸🇪"},
    "267": {"country": "Slovakia",                 "iso2": "SK", "flag": "🇸🇰"},
    "268": {"country": "San Marino",               "iso2": "SM", "flag": "🇸🇲"},
    "269": {"country": "Switzerland",              "iso2": "CH", "flag": "🇨🇭"},
    "271": {"country": "Turkey",                   "iso2": "TR", "flag": "🇹🇷"},
    "272": {"country": "Ukraine",                  "iso2": "UA", "flag": "🇺🇦"},
    "273": {"country": "Russia",                   "iso2": "RU", "flag": "🇷🇺"},
    "274": {"country": "North Macedonia",          "iso2": "MK", "flag": "🇲🇰"},
    "275": {"country": "Latvia",                   "iso2": "LV", "flag": "🇱🇻"},
    "276": {"country": "Estonia",                  "iso2": "EE", "flag": "🇪🇪"},
    "277": {"country": "Lithuania",                "iso2": "LT", "flag": "🇱🇹"},
    "278": {"country": "Slovenia",                 "iso2": "SI", "flag": "🇸🇮"},
    "279": {"country": "Serbia",                   "iso2": "RS", "flag": "🇷🇸"},
    "301": {"country": "Anguilla",                 "iso2": "AI", "flag": "🇦🇮"},
    "303": {"country": "United States of America", "iso2": "US", "flag": "🇺🇸"},
    "304": {"country": "Antigua and Barbuda",      "iso2": "AG", "flag": "🇦🇬"},
    "305": {"country": "Antigua and Barbuda",      "iso2": "AG", "flag": "🇦🇬"},
    "306": {"country": "Netherlands Antilles",     "iso2": "AN", "flag": "🇳🇱"},
    "308": {"country": "Bahamas",                  "iso2": "BS", "flag": "🇧🇸"},
    "309": {"country": "Bahamas",                  "iso2": "BS", "flag": "🇧🇸"},
    "310": {"country": "Bermuda",                  "iso2": "BM", "flag": "🇧🇲"},
    "311": {"country": "Bahamas",                  "iso2": "BS", "flag": "🇧🇸"},
    "312": {"country": "Belize",                   "iso2": "BZ", "flag": "🇧🇿"},
    "314": {"country": "Barbados",                 "iso2": "BB", "flag": "🇧🇧"},
    "316": {"country": "Canada",                   "iso2": "CA", "flag": "🇨🇦"},
    "319": {"country": "Cayman Islands",           "iso2": "KY", "flag": "🇰🇾"},
    "321": {"country": "Costa Rica",               "iso2": "CR", "flag": "🇨🇷"},
    "323": {"country": "Cuba",                     "iso2": "CU", "flag": "🇨🇺"},
    "325": {"country": "Dominica",                 "iso2": "DM", "flag": "🇩🇲"},
    "327": {"country": "Dominican Republic",       "iso2": "DO", "flag": "🇩🇴"},
    "329": {"country": "Guadeloupe",               "iso2": "GP", "flag": "🇬🇵"},
    "330": {"country": "Grenada",                  "iso2": "GD", "flag": "🇬🇩"},
    "331": {"country": "Greenland",                "iso2": "GL", "flag": "🇬🇱"},
    "332": {"country": "Guatemala",                "iso2": "GT", "flag": "🇬🇹"},
    "334": {"country": "Honduras",                 "iso2": "HN", "flag": "🇭🇳"},
    "336": {"country": "Haiti",                    "iso2": "HT", "flag": "🇭🇹"},
    "338": {"country": "United States of America", "iso2": "US", "flag": "🇺🇸"},
    "339": {"country": "Jamaica",                  "iso2": "JM", "flag": "🇯🇲"},
    "341": {"country": "Saint Kitts and Nevis",    "iso2": "KN", "flag": "🇰🇳"},
    "343": {"country": "Saint Lucia",              "iso2": "LC", "flag": "🇱🇨"},
    "345": {"country": "Mexico",                   "iso2": "MX", "flag": "🇲🇽"},
    "347": {"country": "Martinique",               "iso2": "MQ", "flag": "🇲🇶"},
    "348": {"country": "Montserrat",               "iso2": "MS", "flag": "🇲🇸"},
    "350": {"country": "Nicaragua",                "iso2": "NI", "flag": "🇳🇮"},
    "351": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "352": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "353": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "354": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "355": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "356": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "357": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "358": {"country": "Puerto Rico",              "iso2": "PR", "flag": "🇵🇷"},
    "359": {"country": "El Salvador",              "iso2": "SV", "flag": "🇸🇻"},
    "361": {"country": "Saint Pierre and Miquelon","iso2": "PM", "flag": "🇵🇲"},
    "362": {"country": "Trinidad and Tobago",      "iso2": "TT", "flag": "🇹🇹"},
    "364": {"country": "Turks and Caicos Islands", "iso2": "TC", "flag": "🇹🇨"},
    "366": {"country": "United States of America", "iso2": "US", "flag": "🇺🇸"},
    "367": {"country": "United States of America", "iso2": "US", "flag": "🇺🇸"},
    "368": {"country": "United States of America", "iso2": "US", "flag": "🇺🇸"},
    "369": {"country": "United States of America", "iso2": "US", "flag": "🇺🇸"},
    "370": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "371": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "372": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "373": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "374": {"country": "Panama",                   "iso2": "PA", "flag": "🇵🇦"},
    "375": {"country": "Saint Vincent and the Grenadines", "iso2": "VC", "flag": "🇻🇨"},
    "376": {"country": "Saint Vincent and the Grenadines", "iso2": "VC", "flag": "🇻🇨"},
    "377": {"country": "Saint Vincent and the Grenadines", "iso2": "VC", "flag": "🇻🇨"},
    "378": {"country": "British Virgin Islands",   "iso2": "VG", "flag": "🇻🇬"},
    "379": {"country": "US Virgin Islands",        "iso2": "VI", "flag": "🇻🇮"},
    "401": {"country": "Afghanistan",              "iso2": "AF", "flag": "🇦🇫"},
    "403": {"country": "Saudi Arabia",             "iso2": "SA", "flag": "🇸🇦"},
    "405": {"country": "Bangladesh",               "iso2": "BD", "flag": "🇧🇩"},
    "408": {"country": "Bahrain",                  "iso2": "BH", "flag": "🇧🇭"},
    "410": {"country": "Bhutan",                   "iso2": "BT", "flag": "🇧🇹"},
    "412": {"country": "China",                    "iso2": "CN", "flag": "🇨🇳"},
    "413": {"country": "China",                    "iso2": "CN", "flag": "🇨🇳"},
    "414": {"country": "China",                    "iso2": "CN", "flag": "🇨🇳"},
    "416": {"country": "Taiwan",                   "iso2": "TW", "flag": "🇹🇼"},
    "419": {"country": "India",                    "iso2": "IN", "flag": "🇮🇳"},
    "422": {"country": "Iran",                     "iso2": "IR", "flag": "🇮🇷"},
    "423": {"country": "Azerbaijan",               "iso2": "AZ", "flag": "🇦🇿"},
    "425": {"country": "Iraq",                     "iso2": "IQ", "flag": "🇮🇶"},
    "428": {"country": "Israel",                   "iso2": "IL", "flag": "🇮🇱"},
    "431": {"country": "Japan",                    "iso2": "JP", "flag": "🇯🇵"},
    "432": {"country": "Japan",                    "iso2": "JP", "flag": "🇯🇵"},
    "434": {"country": "Turkmenistan",             "iso2": "TM", "flag": "🇹🇲"},
    "436": {"country": "Kazakhstan",               "iso2": "KZ", "flag": "🇰🇿"},
    "438": {"country": "Jordan",                   "iso2": "JO", "flag": "🇯🇴"},
    "440": {"country": "South Korea",              "iso2": "KR", "flag": "🇰🇷"},
    "441": {"country": "South Korea",              "iso2": "KR", "flag": "🇰🇷"},
    "443": {"country": "Palestine",                "iso2": "PS", "flag": "🇵🇸"},
    "445": {"country": "North Korea",              "iso2": "KP", "flag": "🇰🇵"},
    "447": {"country": "Kuwait",                   "iso2": "KW", "flag": "🇰🇼"},
    "450": {"country": "Lebanon",                  "iso2": "LB", "flag": "🇱🇧"},
    "451": {"country": "Kyrgyzstan",               "iso2": "KG", "flag": "🇰🇬"},
    "453": {"country": "Macao",                    "iso2": "MO", "flag": "🇲🇴"},
    "455": {"country": "Maldives",                 "iso2": "MV", "flag": "🇲🇻"},
    "457": {"country": "Mongolia",                 "iso2": "MN", "flag": "🇲🇳"},
    "459": {"country": "Nepal",                    "iso2": "NP", "flag": "🇳🇵"},
    "461": {"country": "Oman",                     "iso2": "OM", "flag": "🇴🇲"},
    "463": {"country": "Pakistan",                 "iso2": "PK", "flag": "🇵🇰"},
    "466": {"country": "Qatar",                    "iso2": "QA", "flag": "🇶🇦"},
    "468": {"country": "Syria",                    "iso2": "SY", "flag": "🇸🇾"},
    "470": {"country": "United Arab Emirates",     "iso2": "AE", "flag": "🇦🇪"},
    "472": {"country": "Uzbekistan",               "iso2": "UZ", "flag": "🇺🇿"},
    "473": {"country": "Vietnam",                  "iso2": "VN", "flag": "🇻🇳"},
    "477": {"country": "Hong Kong",                "iso2": "HK", "flag": "🇭🇰"},
    "478": {"country": "Yemen",                    "iso2": "YE", "flag": "🇾🇪"},
    "501": {"country": "Antarctica",               "iso2": "AQ", "flag": "🇦🇶"},
    "503": {"country": "Australia",                "iso2": "AU", "flag": "🇦🇺"},
    "506": {"country": "Myanmar",                  "iso2": "MM", "flag": "🇲🇲"},
    "508": {"country": "Brunei",                   "iso2": "BN", "flag": "🇧🇳"},
    "510": {"country": "Micronesia",               "iso2": "FM", "flag": "🇫🇲"},
    "511": {"country": "Palau",                    "iso2": "PW", "flag": "🇵🇼"},
    "512": {"country": "New Zealand",              "iso2": "NZ", "flag": "🇳🇿"},
    "514": {"country": "Cambodia",                 "iso2": "KH", "flag": "🇰🇭"},
    "515": {"country": "Cambodia",                 "iso2": "KH", "flag": "🇰🇭"},
    "516": {"country": "Christmas Island",         "iso2": "CX", "flag": "🇨🇽"},
    "518": {"country": "Cook Islands",             "iso2": "CK", "flag": "🇨🇰"},
    "520": {"country": "Fiji",                     "iso2": "FJ", "flag": "🇫🇯"},
    "523": {"country": "Cocos Islands",            "iso2": "CC", "flag": "🇨🇨"},
    "525": {"country": "Indonesia",                "iso2": "ID", "flag": "🇮🇩"},
    "529": {"country": "Kiribati",                 "iso2": "KI", "flag": "🇰🇮"},
    "531": {"country": "Laos",                     "iso2": "LA", "flag": "🇱🇦"},
    "533": {"country": "Malaysia",                 "iso2": "MY", "flag": "🇲🇾"},
    "536": {"country": "Northern Mariana Islands", "iso2": "MP", "flag": "🇲🇵"},
    "538": {"country": "Marshall Islands",         "iso2": "MH", "flag": "🇲🇭"},
    "540": {"country": "New Caledonia",            "iso2": "NC", "flag": "🇳🇨"},
    "542": {"country": "Niue",                     "iso2": "NU", "flag": "🇳🇺"},
    "544": {"country": "Nauru",                    "iso2": "NR", "flag": "🇳🇷"},
    "546": {"country": "French Polynesia",         "iso2": "PF", "flag": "🇵🇫"},
    "548": {"country": "Philippines",              "iso2": "PH", "flag": "🇵🇭"},
    "553": {"country": "Papua New Guinea",         "iso2": "PG", "flag": "🇵🇬"},
    "555": {"country": "Pitcairn Island",          "iso2": "PN", "flag": "🇵🇳"},
    "557": {"country": "Solomon Islands",          "iso2": "SB", "flag": "🇸🇧"},
    "559": {"country": "American Samoa",           "iso2": "AS", "flag": "🇦🇸"},
    "561": {"country": "Samoa",                    "iso2": "WS", "flag": "🇼🇸"},
    "563": {"country": "Singapore",                "iso2": "SG", "flag": "🇸🇬"},
    "564": {"country": "Singapore",                "iso2": "SG", "flag": "🇸🇬"},
    "565": {"country": "Singapore",                "iso2": "SG", "flag": "🇸🇬"},
    "566": {"country": "Singapore",                "iso2": "SG", "flag": "🇸🇬"},
    "567": {"country": "Thailand",                 "iso2": "TH", "flag": "🇹🇭"},
    "570": {"country": "Tonga",                    "iso2": "TO", "flag": "🇹🇴"},
    "572": {"country": "Tuvalu",                   "iso2": "TV", "flag": "🇹🇻"},
    "574": {"country": "Vietnam",                  "iso2": "VN", "flag": "🇻🇳"},
    "576": {"country": "Vanuatu",                  "iso2": "VU", "flag": "🇻🇺"},
    "578": {"country": "Wallis and Futuna",        "iso2": "WF", "flag": "🇼🇫"},
    "601": {"country": "South Africa",             "iso2": "ZA", "flag": "🇿🇦"},
    "603": {"country": "Angola",                   "iso2": "AO", "flag": "🇦🇴"},
    "605": {"country": "Algeria",                  "iso2": "DZ", "flag": "🇩🇿"},
    "607": {"country": "Saint Paul Island",        "iso2": "FR", "flag": "🇫🇷"},
    "608": {"country": "Ascension Island",         "iso2": "SH", "flag": "🇸🇭"},
    "609": {"country": "Burundi",                  "iso2": "BI", "flag": "🇧🇮"},
    "610": {"country": "Benin",                    "iso2": "BJ", "flag": "🇧🇯"},
    "611": {"country": "Botswana",                 "iso2": "BW", "flag": "🇧🇼"},
    "612": {"country": "Central African Republic", "iso2": "CF", "flag": "🇨🇫"},
    "613": {"country": "Cameroon",                 "iso2": "CM", "flag": "🇨🇲"},
    "615": {"country": "Congo",                    "iso2": "CG", "flag": "🇨🇬"},
    "616": {"country": "Comoros",                  "iso2": "KM", "flag": "🇰🇲"},
    "617": {"country": "Cape Verde",               "iso2": "CV", "flag": "🇨🇻"},
    "618": {"country": "Antarctica",               "iso2": "AQ", "flag": "🇦🇶"},
    "619": {"country": "Ivory Coast",              "iso2": "CI", "flag": "🇨🇮"},
    "620": {"country": "Comoros",                  "iso2": "KM", "flag": "🇰🇲"},
    "621": {"country": "Djibouti",                 "iso2": "DJ", "flag": "🇩🇯"},
    "622": {"country": "Egypt",                    "iso2": "EG", "flag": "🇪🇬"},
    "624": {"country": "Ethiopia",                 "iso2": "ET", "flag": "🇪🇹"},
    "625": {"country": "Eritrea",                  "iso2": "ER", "flag": "🇪🇷"},
    "626": {"country": "Gabon",                    "iso2": "GA", "flag": "🇬🇦"},
    "627": {"country": "Ghana",                    "iso2": "GH", "flag": "🇬🇭"},
    "629": {"country": "Gambia",                   "iso2": "GM", "flag": "🇬🇲"},
    "630": {"country": "Guinea-Bissau",            "iso2": "GW", "flag": "🇬🇼"},
    "631": {"country": "Equatorial Guinea",        "iso2": "GQ", "flag": "🇬🇶"},
    "632": {"country": "Guinea",                   "iso2": "GN", "flag": "🇬🇳"},
    "633": {"country": "Burkina Faso",             "iso2": "BF", "flag": "🇧🇫"},
    "634": {"country": "Kenya",                    "iso2": "KE", "flag": "🇰🇪"},
    "635": {"country": "Antarctica",               "iso2": "AQ", "flag": "🇦🇶"},
    "636": {"country": "Liberia",                  "iso2": "LR", "flag": "🇱🇷"},
    "637": {"country": "Liberia",                  "iso2": "LR", "flag": "🇱🇷"},
    "638": {"country": "South Sudan",              "iso2": "SS", "flag": "🇸🇸"},
    "642": {"country": "Libya",                    "iso2": "LY", "flag": "🇱🇾"},
    "644": {"country": "Lesotho",                  "iso2": "LS", "flag": "🇱🇸"},
    "645": {"country": "Mauritius",                "iso2": "MU", "flag": "🇲🇺"},
    "647": {"country": "Madagascar",               "iso2": "MG", "flag": "🇲🇬"},
    "649": {"country": "Mali",                     "iso2": "ML", "flag": "🇲🇱"},
    "650": {"country": "Mozambique",               "iso2": "MZ", "flag": "🇲🇿"},
    "654": {"country": "Mauritania",               "iso2": "MR", "flag": "🇲🇷"},
    "655": {"country": "Malawi",                   "iso2": "MW", "flag": "🇲🇼"},
    "656": {"country": "Niger",                    "iso2": "NE", "flag": "🇳🇪"},
    "657": {"country": "Nigeria",                  "iso2": "NG", "flag": "🇳🇬"},
    "659": {"country": "Namibia",                  "iso2": "NA", "flag": "🇳🇦"},
    "660": {"country": "Reunion",                  "iso2": "RE", "flag": "🇷🇪"},
    "661": {"country": "Rwanda",                   "iso2": "RW", "flag": "🇷🇼"},
    "662": {"country": "Sudan",                    "iso2": "SD", "flag": "🇸🇩"},
    "663": {"country": "Senegal",                  "iso2": "SN", "flag": "🇸🇳"},
    "664": {"country": "Seychelles",               "iso2": "SC", "flag": "🇸🇨"},
    "665": {"country": "Saint Helena",             "iso2": "SH", "flag": "🇸🇭"},
    "666": {"country": "Somalia",                  "iso2": "SO", "flag": "🇸🇴"},
    "667": {"country": "Sierra Leone",             "iso2": "SL", "flag": "🇸🇱"},
    "668": {"country": "São Tomé and Príncipe",    "iso2": "ST", "flag": "🇸🇹"},
    "669": {"country": "Swaziland",                "iso2": "SZ", "flag": "🇸🇿"},
    "670": {"country": "Chad",                     "iso2": "TD", "flag": "🇹🇩"},
    "671": {"country": "Togo",                     "iso2": "TG", "flag": "🇹🇬"},
    "672": {"country": "Tunisia",                  "iso2": "TN", "flag": "🇹🇳"},
    "674": {"country": "Tanzania",                 "iso2": "TZ", "flag": "🇹🇿"},
    "675": {"country": "Uganda",                   "iso2": "UG", "flag": "🇺🇬"},
    "676": {"country": "DR Congo",                 "iso2": "CD", "flag": "🇨🇩"},
    "677": {"country": "Tanzania",                 "iso2": "TZ", "flag": "🇹🇿"},
    "678": {"country": "Zambia",                   "iso2": "ZM", "flag": "🇿🇲"},
    "679": {"country": "Zimbabwe",                 "iso2": "ZW", "flag": "🇿🇼"},
    # Added 2026-10-05: absent before, so 31 of 1,743 live vessels had no
    # flag. Malta's 229 alone, and all of South America.
    "229": {"country": "Malta", "iso2": "MT", "flag": "🇲🇹"},
    "270": {"country": "Czech Republic", "iso2": "CZ", "flag": "🇨🇿"},
    "471": {"country": "United Arab Emirates", "iso2": "AE", "flag": "🇦🇪"},
    "577": {"country": "Vanuatu", "iso2": "VU", "flag": "🇻🇺"},
    "701": {"country": "Argentina", "iso2": "AR", "flag": "🇦🇷"},
    "710": {"country": "Brazil", "iso2": "BR", "flag": "🇧🇷"},
    "720": {"country": "Bolivia", "iso2": "BO", "flag": "🇧🇴"},
    "725": {"country": "Chile", "iso2": "CL", "flag": "🇨🇱"},
    "730": {"country": "Colombia", "iso2": "CO", "flag": "🇨🇴"},
    "735": {"country": "Ecuador", "iso2": "EC", "flag": "🇪🇨"},
    "740": {"country": "Falkland Islands", "iso2": "FK", "flag": "🇫🇰"},
    "745": {"country": "French Guiana", "iso2": "GF", "flag": "🇬🇫"},
    "750": {"country": "Guyana", "iso2": "GY", "flag": "🇬🇾"},
    "755": {"country": "Paraguay", "iso2": "PY", "flag": "🇵🇾"},
    "760": {"country": "Peru", "iso2": "PE", "flag": "🇵🇪"},
    "765": {"country": "Suriname", "iso2": "SR", "flag": "🇸🇷"},
    "770": {"country": "Uruguay", "iso2": "UY", "flag": "🇺🇾"},
    "775": {"country": "Venezuela", "iso2": "VE", "flag": "🇻🇪"},
}


def mid_of(mmsi) -> str:
    """The MID inside an MMSI, by where ITU-R M.585 puts it, or "".

    The first three digits are the MID only for a ship: nine digits,
    leading 2-7. A coast station is 00+MID, a group 0+MID, a SAR aircraft
    111+MID, a craft associated with a parent ship 98+MID, an aid to
    navigation 99+MID. 970/972/974 (SART, MOB, EPIRB) carry no MID at
    all. Reading the first three digits of those gives a confident flag
    that is not theirs.
    """
    d = str(mmsi or "").strip()
    if len(d) != 9 or not d.isdigit():
        return ""
    if d[0] in "234567":
        return d[:3]
    if d.startswith("111"):
        return d[3:6]
    if d.startswith(("98", "99")):
        return d[2:5]
    if d.startswith("00"):
        return d[2:5]
    if d.startswith("0"):
        return d[1:4]
    return ""


def lookup_mmsi(mmsi: str) -> dict:
    """Get country/flag info from MMSI number (first 3 digits = MID)."""
    mid = mid_of(mmsi)
    info = MID_TABLE.get(mid, {"country": "Unknown", "iso2": "XX", "flag": "🏳"})
    return {
        "mmsi":         mmsi,
        "mid":          mid,
        "flag_country": info["country"],
        "flag_iso2":    info["iso2"],
        "flag_emoji":   info["flag"],
        "flag_url":     f"https://flagcdn.com/w40/{info['iso2'].lower()}.png"
                        if info["iso2"] != "XX" else None,
    }
