/**
 * aircraftModels.js — which airframe to draw for an ADS-B contact.
 *
 * The models are generated by tools/make_aircraft_models.py, one per
 * FAMILY rather than per type. A 737 and an A320 differ in details
 * smaller than a pixel at any altitude this map is used at; what reads
 * on screen, and what these carry, is narrowbody against widebody,
 * twin against quad, jet against turboprop, airliner against fighter
 * against helicopter.
 *
 * Type designator first because it is exact, ADS-B emitter category
 * second because it is always present, and nothing at all rather than
 * a guess when neither says anything.
 */

export const FAMILIES = [
    "narrowbody", "widebody", "heavy4", "regional",
    "turboprop", "lightprop", "fighter", "helicopter",
]

export const modelUrl = (family) =>
    FAMILIES.includes(family) ? `/models/aircraft/${family}.glb` : null

/** Exact ICAO type designators, where the family is not guessable. */
const BY_TYPE = {}
const put = (family, ...types) => types.forEach((t) => { BY_TYPE[t] = family })

put("heavy4", "A388", "B741", "B742", "B743", "B744", "B748", "B74S",
    "A342", "A343", "A345", "A346", "IL96", "AN24")
put("widebody", "B762", "B763", "B764", "B772", "B773", "B77L", "B77W",
    "B788", "B789", "B78X", "A306", "A310", "A332", "A333", "A337", "A338",
    "A339", "A359", "A35K", "MD11", "IL76", "C17", "A124", "B52", "K35R", "C5M")
put("regional", "E170", "E75L", "E75S", "E190", "E195", "E290", "E295",
    "CRJ1", "CRJ2", "CRJ7", "CRJ9", "CRJX", "RJ85", "RJ1H", "SU95", "F70", "F100")
put("turboprop", "AT43", "AT45", "AT72", "AT75", "AT76", "DH8A", "DH8B",
    "DH8C", "DH8D", "SF34", "SB20", "E120", "JS32", "JS41", "D228", "C130",
    "C30J", "A400", "CN35", "AN26")
put("lightprop", "C172", "C182", "C206", "C208", "PC12", "PC6T", "BE20",
    "BE9L", "BE58", "P28A", "P28R", "SR20", "SR22", "DA40", "DA42", "TBM7",
    "TBM8", "TBM9", "M20P", "C152")
put("fighter", "F16", "F15", "F18", "F35", "A10", "EUFI", "RFAL", "TOR",
    "GR4", "MIG9", "SU25", "SU27", "SU30", "SU34", "HAWK", "L39", "F2TH")
put("helicopter", "EC35", "EC45", "EC20", "H145", "H135", "H160", "A109",
    "A139", "AS50", "AS55", "B06", "B407", "B412", "B429", "R44", "R66",
    "S76", "S92", "UH60", "CH47", "NH90", "H500")

/**
 * ADS-B emitter category.
 *
 * A* is airborne, B* is gliders/balloons/UAVs, and C* is SURFACE:
 * service vehicles, emergency vehicles and fixed obstructions. Around
 * 5% of a live sample are C* — pushback tugs and towers sitting on the
 * apron — and drawing those as aircraft is simply wrong.
 */
const BY_CATEGORY = {
    A1: "lightprop", A2: "lightprop", A3: "narrowbody",
    A4: "widebody", A5: "widebody", A6: "fighter", A7: "helicopter",
}

/** Is this contact a surface vehicle or obstruction rather than an aircraft? */
export function isSurfaceVehicle(ac) {
    const c = String(ac?.category || "").toUpperCase()
    return c.startsWith("C")
}

/**
 * The model family for a contact, or null when there is nothing to go on.
 *
 * Null means draw the flat glyph — an unidentified return should not be
 * given a specific airframe it was never reported to have.
 */
export function familyFor(ac) {
    if (!ac || isSurfaceVehicle(ac)) return null
    const type = String(ac.type || ac.aircraft_type || "").trim().toUpperCase()
    if (BY_TYPE[type]) return BY_TYPE[type]

    if (type) {
        // Families are legible from the designator's stem for the common
        // series, which covers types not worth listing one by one.
        if (/^A3(1[89]|2[01])/.test(type) || /^A(19|20|21)N$/.test(type)) return "narrowbody"
        if (/^B7(3[3-9]|1[25])/.test(type) || /^B3[789]M$/.test(type)) return "narrowbody"
        if (/^BCS[13]$/.test(type) || /^MD8[0-9]$/.test(type)) return "narrowbody"
        if (/^(F1[56]|EUFI|RFAL|MIG|SU[0-9])/.test(type)) return "fighter"
    }
    return BY_CATEGORY[String(ac.category || "").toUpperCase()] || null
}

/**
 * Heading for Cesium's headingPitchRollQuaternion, in radians.
 *
 * MEASURED, NOT ASSUMED: with hpr.heading = 0 the model's +X axis points
 * EAST, so a compass track needs 90° removed. Verified against Cesium
 * directly — heading 0/90/180/270 gave nose bearings 90/180/270/0, with
 * the nose's vertical component exactly 0 every time, which is why the
 * airframe sits level with the horizon whatever the camera does.
 */
export function modelHeadingRadians(trackDeg) {
    const t = Number(trackDeg)
    return (((Number.isFinite(t) ? t : 0) - 90) * Math.PI) / 180
}
