/**
 * vesselModels.js — which hull to draw for an AIS contact.
 *
 * Generated by tools/make_vessel_models.py. Same axis handling as the
 * aircraft, and the same restraint about what a model claims.
 *
 * WHAT A HULL CLAIMS. Two things, and both are thinner than they look:
 *
 *   - SIZE. AIS as we receive it carries no length or beam — 0 of 1,728
 *     vessels in a live sample had either — so a hull's size on the map
 *     is a nominal figure for its type, not a measurement of that ship.
 *   - DIRECTION. A hull points somewhere. A vessel with no usable
 *     heading keeps the flat glyph instead, because a glyph pointing
 *     nowhere in particular is honest and a ship pointing north is not.
 *     That is 44% of them: 972 of 1,728 had a usable heading, and there
 *     is no course-over-ground field in this feed to fall back on.
 */
import { vesselShipType } from "./iconUtils.js"
import { vesselHeading } from "./markerOrientation.js"

export const FAMILIES = ["container", "cargo", "tanker", "passenger",
                         "military", "fishing", "other"]

/** See aircraftModels.js — bumped whenever the hulls are regenerated. */
export const MODEL_VERSION = 6

export const modelUrl = (family) =>
    FAMILIES.includes(family)
        ? `/models/vessel/${family}.glb?v=${MODEL_VERSION}` : null

/**
 * The hull family for a vessel.
 *
 * vesselShipType already buckets AIS ship types for the glyphs, and
 * reusing it keeps a vessel's hull and its icon telling the same story.
 * Most vessels land on "other": 34% of a live sample report that type
 * and another 34% report nothing at all.
 */
export function familyFor(vessel) {
    if (!vessel) return null
    const t = vesselShipType(vessel)
    return FAMILIES.includes(t) ? t : "other"
}

/**
 * Heading for Cesium's headingPitchRollQuaternion, in radians, or null
 * when the vessel has not told us which way it is facing.
 *
 * Null means "draw the glyph". The offset is the same measured constant
 * the aircraft use — see aircraftModels.js for why it is measured
 * rather than derived — and applies here because the hulls are built to
 * the same convention.
 */
const HEADING_OFFSET_DEG = 270

export function modelHeadingRadians(vessel) {
    const hdg = vesselHeading(vessel)
    if (hdg === null) return null
    return headingRadiansFromDegrees(hdg)
}

/**
 * The same conversion for a heading we worked out ourselves — a course
 * derived from movement, or 0 for a vessel whose orientation nobody has
 * reported. Separate entry point because the caller, not this module,
 * is the one that knows where the number came from.
 */
export function headingRadiansFromDegrees(deg) {
    const d = Number(deg)
    return (((Number.isFinite(d) ? d : 0) + HEADING_OFFSET_DEG) * Math.PI) / 180
}
